song_list = [
    "Indian 2 BGMs - Paaraa Song Sad BGM _ Paaraa Flute Version _ Anirudh BGMs-yt.savetube.me.mp3"
    "Maryan Love Background Music (BGM) _ South Movies BGM-yt.savetube.me.mp3"
    "SpotiDownloader.com - BLUE LOCK EKI - NUEKI.mp3"
    "SpotiDownloader.com - En Magane (From _Kuberaa_)(Tamil) - Devi Sri Prasad.mp3"
    "SpotiDownloader.com - En Vizhiyin Kanavu - Gopi Sundar.mp3"
    "SpotiDownloader.com - KU LO SA (with Camila Cabello) - Oxlade.mp3"
    "SpotiDownloader.com - London Bridge Is Falling Down My Fair Lady - Arianna Phillps Music.mp3"
    "SpotiDownloader.com - MATUSHKA ULTRAFUNK - satirin.mp3"
    "SpotiDownloader.com - Set Fire to the Rain - Adele.mp3"
    "SpotiDownloader.com - Матушка - Татьяна Куртукова.mp3"
    "The Soul Of Appanna Bgm Ringtone _ Game Changer _ Ram Charan _ Anjali _ Thaman S-yt.savetube.me.mp3"
    "Yenga Pona Raasa BGM.mp4"
    "[SPOTDOWNLOADER.COM] Adheeraa (From _Cobra_).mp3"
    "[SPOTDOWNLOADER.COM] Akuma no Ko.mp3"
    "[SPOTDOWNLOADER.COM] All The Things She Said.mp3"
    "[SPOTDOWNLOADER.COM] All Time Low.mp3"
    "[SPOTDOWNLOADER.COM] Am I Dreaming (Metro Boomin & A$AP Rocky, Roisee).mp3"
    "[SPOTDOWNLOADER.COM] Ambikapathy.mp3"
    "[SPOTDOWNLOADER.COM] Anbil Avan.mp3"
    "[SPOTDOWNLOADER.COM] Another Love.mp3"
    "[SPOTDOWNLOADER.COM] Arcade.mp3"
    "[SPOTDOWNLOADER.COM] Ashes - from _Deadpool 2_ Motion Picture Soundtrack.mp3"
    "[SPOTDOWNLOADER.COM] Ava.mp3"
    "[SPOTDOWNLOADER.COM] Bad Liar.mp3"
    "[SPOTDOWNLOADER.COM] Be Alright.mp3"
    "[SPOTDOWNLOADER.COM] Chaleya (From _Jawan_).mp3"
    "[SPOTDOWNLOADER.COM] Cheap Thrills.mp3"
    "[SPOTDOWNLOADER.COM] Chuttamalle (From _Devara Part 1_).mp3"
    "[SPOTDOWNLOADER.COM] Counting Stars.mp3"
    "[SPOTDOWNLOADER.COM] Cradles.mp3"
    "[SPOTDOWNLOADER.COM] Danza Kuduro.mp3"
    "[SPOTDOWNLOADER.COM] Dead To Me - Slow + Reverb.mp3"
    "[SPOTDOWNLOADER.COM] Demons.mp3"
    "[SPOTDOWNLOADER.COM] Do You Feel It_.mp3"
    "[SPOTDOWNLOADER.COM] Dynasty.mp3"
    "[SPOTDOWNLOADER.COM] End of Beginning.mp3"
    "[SPOTDOWNLOADER.COM] Engae Endru Povathu.mp3"
    "[SPOTDOWNLOADER.COM] Ennoda Laila.mp3"
    "[SPOTDOWNLOADER.COM] EP. 1_ Adult.mp3"
    "[SPOTDOWNLOADER.COM] EP. 2_ Friends.mp3"
    "[SPOTDOWNLOADER.COM] EP. 4_ Important.mp3"
    "[SPOTDOWNLOADER.COM] Evanda Enakku Custody (From _Mahaan_).mp3"
    "[SPOTDOWNLOADER.COM] Everyday Normal Guy 2.mp3"
    "[SPOTDOWNLOADER.COM] Fairytale.mp3"
    "[SPOTDOWNLOADER.COM] Fine.mp3"
    "[SPOTDOWNLOADER.COM] Fireflies.mp3"
    "[SPOTDOWNLOADER.COM] Forever Young.mp3"
    "[SPOTDOWNLOADER.COM] Gangsta's Paradise.mp3"
    "[SPOTDOWNLOADER.COM] Good Life (with G-Eazy & Kehlani).mp3"
    "[SPOTDOWNLOADER.COM] Hall of Fame (feat. will.i.am).mp3"
    "[SPOTDOWNLOADER.COM] Hayyoda (From _Jawan_).mp3"
    "[SPOTDOWNLOADER.COM] Heat Waves.mp3"
    "[SPOTDOWNLOADER.COM] Home (with Machine Gun Kelly, X Ambassadors & Bebe Rexha).mp3"
    "[SPOTDOWNLOADER.COM] House of Memories.mp3"
    "[SPOTDOWNLOADER.COM] How You Like That.mp3"
    "[SPOTDOWNLOADER.COM] Hurt.mp3"
    "[SPOTDOWNLOADER.COM] Hymn for the Weekend.mp3"
    "[SPOTDOWNLOADER.COM] I Wanna Be Yours.mp3"
    "[SPOTDOWNLOADER.COM] In Christ Alone (My Hope Is Found) - Secrets Of The Vine Album Version.mp3"
    "[SPOTDOWNLOADER.COM] In The End - Mellen Gi Remix.mp3"
    "[SPOTDOWNLOADER.COM] In The Stars.mp3"
    "[SPOTDOWNLOADER.COM] Jolly O Gymkhana (From _Beast_).mp3"
    "[SPOTDOWNLOADER.COM] Kaadhal En Kaviye.mp3"
    "[SPOTDOWNLOADER.COM] Kaadhalai Solla Mudiyatha.mp3"
    "[SPOTDOWNLOADER.COM] Kani Mozhiyae.mp3"
    "[SPOTDOWNLOADER.COM] Karma Veeran.mp3"
    "[SPOTDOWNLOADER.COM] last day on earth.mp3"
    "[SPOTDOWNLOADER.COM] Legends Never Die.mp3"
    "[SPOTDOWNLOADER.COM] Let Her Go.mp3"
    "[SPOTDOWNLOADER.COM] Lights Are On.mp3"
    "[SPOTDOWNLOADER.COM] Like a Prayer - Choir Version From “Deadpool & Wolverine”.mp3"
    "[SPOTDOWNLOADER.COM] Love Me.mp3"
    "[SPOTDOWNLOADER.COM] Lutt Putt Gaya (From _Dunki_).mp3"
    "[SPOTDOWNLOADER.COM] Maattram Ondrudhaan Maaraadhadhu.mp3"
    "[SPOTDOWNLOADER.COM] Marudaani.mp3"
    "[SPOTDOWNLOADER.COM] Mary On A Cross - Slowed+Reverb.mp3"
    "[SPOTDOWNLOADER.COM] Maybe My Soulmate Died.mp3"
    "[SPOTDOWNLOADER.COM] Mazhai Kuruvi.mp3"
    "[SPOTDOWNLOADER.COM] Mazhai Varum - Female.mp3"
    "[SPOTDOWNLOADER.COM] Missing Me (From _Mahaan (Tamil)_).mp3"
    "[SPOTDOWNLOADER.COM] MONEY.mp3"
    "[SPOTDOWNLOADER.COM] My Everything.mp3"
    "[SPOTDOWNLOADER.COM] my ordinary life (slowed + reverb) - Slowed.mp3"
    "[SPOTDOWNLOADER.COM] Nee Kavithaigala.mp3"
    "[SPOTDOWNLOADER.COM] Nee Singam Dhan.mp3"
    "[SPOTDOWNLOADER.COM] Neela Vaanam.mp3"
    "[SPOTDOWNLOADER.COM] Net ah Thorandha - From _Naa Oru Alien_.mp3"
    "[SPOTDOWNLOADER.COM] Newyork Nagaram.mp3"
    "[SPOTDOWNLOADER.COM] Ninaivirukka (From _Pathu Thala_).mp3"
    "[SPOTDOWNLOADER.COM] Nobody (feat. Matthew West).mp3"
    "[SPOTDOWNLOADER.COM] Numb Little Bug.mp3"
    "[SPOTDOWNLOADER.COM] Oh Maya.mp3"
    "[SPOTDOWNLOADER.COM] Older.mp3"
    "[SPOTDOWNLOADER.COM] Omana Penne.mp3"
    "[SPOTDOWNLOADER.COM] On My Own.mp3"
    "[SPOTDOWNLOADER.COM] Once I Was 7 Years Old.mp3"
    "[SPOTDOWNLOADER.COM] Osaka Osaka.mp3"
    "[SPOTDOWNLOADER.COM] Oxygen.mp3"
    "[SPOTDOWNLOADER.COM] Part of Me (Slowed + Reverb) - This Is Now, Never Gonna Ever Take Away from Me.mp3"
    "[SPOTDOWNLOADER.COM] Past Lives.mp3"
    "[SPOTDOWNLOADER.COM] Paththavaikkum (From _Devara Part 1_).mp3"
    "[SPOTDOWNLOADER.COM] Perfect.mp3"
    "[SPOTDOWNLOADER.COM] Phoenix.mp3"
    "[SPOTDOWNLOADER.COM] Pompeii.mp3"
    "[SPOTDOWNLOADER.COM] Porkanda Singam.mp3"
    "[SPOTDOWNLOADER.COM] Pudhu Suriyan.mp3"
    "[SPOTDOWNLOADER.COM] Quit Pannuda.mp3"
    "[SPOTDOWNLOADER.COM] Remember the Name (feat. Styles of Beyond).mp3"
    "[SPOTDOWNLOADER.COM] Replay.mp3"
    "[SPOTDOWNLOADER.COM] Right Now (Na Na Na).mp3"
    "[SPOTDOWNLOADER.COM] Royalty.mp3"
    "[SPOTDOWNLOADER.COM] Sadness and Sorrow (Naruto).mp3"
    "[SPOTDOWNLOADER.COM] Say Yes To Heaven.mp3"
    "[SPOTDOWNLOADER.COM] Sevatha Pulla.mp3"
    "[SPOTDOWNLOADER.COM] Sirukki Vaasam.mp3"
    "[SPOTDOWNLOADER.COM] Smile.mp3"
    "[SPOTDOWNLOADER.COM] So Big.mp3"
    "[SPOTDOWNLOADER.COM] So Busted.mp3"
    "[SPOTDOWNLOADER.COM] Someone You Loved.mp3"
    "[SPOTDOWNLOADER.COM] Something Just Like This.mp3"
    "[SPOTDOWNLOADER.COM] Space Song.mp3"
    "[SPOTDOWNLOADER.COM] Stand By Me (Poovulagamaa).mp3"
    "[SPOTDOWNLOADER.COM] Stereo Hearts (feat. Adam Levine).mp3"
    "[SPOTDOWNLOADER.COM] Stressed Out.mp3"
    "[SPOTDOWNLOADER.COM] Summertime Sadness.mp3"
    "[SPOTDOWNLOADER.COM] Sweater Weather.mp3"
    "[SPOTDOWNLOADER.COM] Take Me Home, Country Roads - Original Version.mp3"
    "[SPOTDOWNLOADER.COM] Take On Me - MTV Unplugged.mp3"
    "[SPOTDOWNLOADER.COM] Tharangini.mp3"
    "[SPOTDOWNLOADER.COM] The God Who Stays.mp3"
    "[SPOTDOWNLOADER.COM] The Nights.mp3"
    "[SPOTDOWNLOADER.COM] The Rumbling.mp3"
    "[SPOTDOWNLOADER.COM] The Scientist.mp3"
    "[SPOTDOWNLOADER.COM] The Search.mp3"
    "[SPOTDOWNLOADER.COM] The Sound of Silence.mp3"
    "[SPOTDOWNLOADER.COM] Toxic.mp3"
    "[SPOTDOWNLOADER.COM] Treachery.mp3"
    "[SPOTDOWNLOADER.COM] Ullaallaa - From _Petta_.mp3"
    "[SPOTDOWNLOADER.COM] Un Vizhigalil (From _Darling_).mp3"
    "[SPOTDOWNLOADER.COM] Unai Serndhidavey.mp3"
    "[SPOTDOWNLOADER.COM] Unstoppable.mp3"
    "[SPOTDOWNLOADER.COM] Uyir Urugudhey.mp3"
    "[SPOTDOWNLOADER.COM] Vaadi Ne Va.mp3"
    "[SPOTDOWNLOADER.COM] Veesum Velichathile.mp3"
    "[SPOTDOWNLOADER.COM] Viva La Vida.mp3"
    "[SPOTDOWNLOADER.COM] Wait.mp3"
    "[SPOTDOWNLOADER.COM] We Don't Talk Anymore (feat. Selena Gomez).mp3"
    "[SPOTDOWNLOADER.COM] We Own It (Fast & Furious).mp3"
    "[SPOTDOWNLOADER.COM] When Can I See You Again_ - From _Wreck-It Ralph__Soundtrack Version.mp3"
    "[SPOTDOWNLOADER.COM] Whistle Baby.mp3"
    "[SPOTDOWNLOADER.COM] Yesterday (Originally By The Beatles).mp3"
    "[SPOTDOWNLOADER.COM] You're Perfect.mp3"
    "[SPOTDOWNLOADER.COM] Your Love Is My Drug (8 Bit Slowed).mp3"
]

for song in song_list:
    clean = song.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    print(f'''
  <div class="song">
    <div class="filename">{clean}</div>
    <audio controls preload="none">
      <source src="{clean}" type="audio/mpeg">
      Your browser does not support the audio element.
    </audio>
  </div>
''')
